






















#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;




namespace Foundation.Serialization
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }


	}
}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IFTFTenant Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/FTFTenant</para>	
	/// <para>ID: 00ad6538-7140-4703-affe-0082755bc0a8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFTFTenantConstants.TemplateIdString )] //, Cachable = true
	public partial interface IFTFTenant : IGlassBase 
	{
			
	}


	public static partial class IFTFTenantConstants{

			public const string TemplateIdString = "00ad6538-7140-4703-affe-0082755bc0a8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "FTFTenant";

			

	}

	
	/// <summary>
	/// FTFTenant
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/FTFTenant</para>	
	/// <para>ID: 00ad6538-7140-4703-affe-0082755bc0a8</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFTFTenantConstants.TemplateIdString)] //, Cachable = true
	public partial class FTFTenant  : GlassBase, IFTFTenant 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Base_Content_Body Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Content Body</para>	
	/// <para>ID: 07678ef9-0560-4a36-a753-fa5d533491ea</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Content_BodyConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Content_Body : IGlassBase 
	{
			
					/// <summary>
					/// The ContentBody field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2156b954-9392-49f8-b1ec-0d3a6429ab54</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Content_BodyConstants.ContentBodyFieldName)]
					string ContentBody  {get; set;}
			
			
	}


	public static partial class I_Base_Content_BodyConstants{

			public const string TemplateIdString = "07678ef9-0560-4a36-a753-fa5d533491ea";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Content Body";

		
			
			public static readonly ID ContentBodyFieldId = new ID("2156b954-9392-49f8-b1ec-0d3a6429ab54");
			public const string ContentBodyFieldName = "ContentBody";
			
			

	}

	
	/// <summary>
	/// _Base_Content_Body
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Content Body</para>	
	/// <para>ID: 07678ef9-0560-4a36-a753-fa5d533491ea</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Content_BodyConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Content_Body  : GlassBase, I_Base_Content_Body 
	{
	   
		
				/// <summary>
				/// The ContentBody field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2156b954-9392-49f8-b1ec-0d3a6429ab54</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Content_BodyConstants.ContentBodyFieldName)]
				public virtual string ContentBody  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ISlideFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/SlideFolder</para>	
	/// <para>ID: 09784985-585f-461c-b28e-67f40927fe02</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISlideFolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISlideFolder : IGlassBase 
	{
			
	}


	public static partial class ISlideFolderConstants{

			public const string TemplateIdString = "09784985-585f-461c-b28e-67f40927fe02";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SlideFolder";

			

	}

	
	/// <summary>
	/// SlideFolder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/SlideFolder</para>	
	/// <para>ID: 09784985-585f-461c-b28e-67f40927fe02</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISlideFolderConstants.TemplateIdString)] //, Cachable = true
	public partial class SlideFolder  : GlassBase, ISlideFolder 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IHomePage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/HomePage</para>	
	/// <para>ID: 0e7c95d7-43da-4665-a925-41454201c2ef</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomePageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHomePage : IGlassBase , global::Foundation.Serialization.I_Content, global::Foundation.Serialization.I_PageNotFound
	{
			
	}


	public static partial class IHomePageConstants{

			public const string TemplateIdString = "0e7c95d7-43da-4665-a925-41454201c2ef";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "HomePage";

		
			
			public static readonly ID ContentFieldId = new ID("69047b4f-add7-4734-b55f-d329a44f72aa");
			public const string ContentFieldName = "Content";
			
		
			
			public static readonly ID ErrorPageFieldId = new ID("caef0675-bdca-467e-9270-d0c925aecc74");
			public const string ErrorPageFieldName = "ErrorPage";
			
			

	}

	
	/// <summary>
	/// HomePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/HomePage</para>	
	/// <para>ID: 0e7c95d7-43da-4665-a925-41454201c2ef</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHomePageConstants.TemplateIdString)] //, Cachable = true
	public partial class HomePage  : GlassBase, IHomePage 
	{
	   
		
				/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 69047b4f-add7-4734-b55f-d329a44f72aa</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
		
				/// <summary>
				/// The ErrorPage field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: caef0675-bdca-467e-9270-d0c925aecc74</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHomePageConstants.ErrorPageFieldName)]
				public virtual Link ErrorPage  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IRecipeMultiList Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipeMultiList</para>	
	/// <para>ID: 26d7522a-2e2f-47ab-9258-084c1f8f9617</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeMultiListConstants.TemplateIdString )] //, Cachable = true
	public partial interface IRecipeMultiList : IGlassBase 
	{
			
					/// <summary>
					/// The Headline field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 29382791-1acf-41ab-905f-05a748b028ca</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeMultiListConstants.HeadlineFieldName)]
					string Headline  {get; set;}
			
			
					/// <summary>
					/// The RecipesList field.
					/// <para></para>
					/// <para>Field Type: Treelist</para>		
					/// <para>Field ID: c2305de1-32c6-431c-beee-8a309569e9e0</para>
					/// <para>Custom Data: generic=RecipeDetail</para>
					/// </summary>
					[SitecoreField(IRecipeMultiListConstants.RecipesListsFieldName)]
					IEnumerable<RecipeDetail> RecipesLists  {get; set;}
			
			
	}


	public static partial class IRecipeMultiListConstants{

			public const string TemplateIdString = "26d7522a-2e2f-47ab-9258-084c1f8f9617";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "RecipeMultiList";

		
			
			public static readonly ID HeadlineFieldId = new ID("29382791-1acf-41ab-905f-05a748b028ca");
			public const string HeadlineFieldName = "Headline";
			
		
			
			public static readonly ID RecipesListsFieldId = new ID("c2305de1-32c6-431c-beee-8a309569e9e0");
			public const string RecipesListsFieldName = "RecipesList";
			
			

	}

	
	/// <summary>
	/// RecipeMultiList
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipeMultiList</para>	
	/// <para>ID: 26d7522a-2e2f-47ab-9258-084c1f8f9617</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeMultiListConstants.TemplateIdString)] //, Cachable = true
	public partial class RecipeMultiList  : GlassBase, IRecipeMultiList 
	{
	   
		
				/// <summary>
				/// The Headline field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 29382791-1acf-41ab-905f-05a748b028ca</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeMultiListConstants.HeadlineFieldName)]
				public virtual string Headline  {get; set;}
					
		
				/// <summary>
				/// The RecipesList field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: c2305de1-32c6-431c-beee-8a309569e9e0</para>
				/// <para>Custom Data: generic=RecipeDetail</para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeMultiListConstants.RecipesListsFieldName)]
				public virtual IEnumerable<RecipeDetail> RecipesLists  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Title Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Title</para>	
	/// <para>ID: 3611a0e6-e692-4186-88ee-42afce9b7d86</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_TitleConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Title : IGlassBase 
	{
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: ae26dccd-dfce-4443-a5dc-6f219439e23e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_TitleConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class I_TitleConstants{

			public const string TemplateIdString = "3611a0e6-e692-4186-88ee-42afce9b7d86";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Title";

		
			
			public static readonly ID TitleFieldId = new ID("ae26dccd-dfce-4443-a5dc-6f219439e23e");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// _Title
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Title</para>	
	/// <para>ID: 3611a0e6-e692-4186-88ee-42afce9b7d86</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_TitleConstants.TemplateIdString)] //, Cachable = true
	public partial class _Title  : GlassBase, I_Title 
	{
	   
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ae26dccd-dfce-4443-a5dc-6f219439e23e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_TitleConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Base_Image Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Image</para>	
	/// <para>ID: 474ec3c6-0bef-4736-bfef-d110cfa1610c</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ImageConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Image : IGlassBase 
	{
			
					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Multilist</para>		
					/// <para>Field ID: fc580838-74b5-4372-b1f4-4464eba81d95</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_ImageConstants.ImagesFieldName)]
					IEnumerable<Guid> Images  {get; set;}
			
			
	}


	public static partial class I_Base_ImageConstants{

			public const string TemplateIdString = "474ec3c6-0bef-4736-bfef-d110cfa1610c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Image";

		
			
			public static readonly ID ImagesFieldId = new ID("fc580838-74b5-4372-b1f4-4464eba81d95");
			public const string ImagesFieldName = "Image";
			
			

	}

	
	/// <summary>
	/// _Base_Image
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Image</para>	
	/// <para>ID: 474ec3c6-0bef-4736-bfef-d110cfa1610c</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ImageConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Image  : GlassBase, I_Base_Image 
	{
	   
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: fc580838-74b5-4372-b1f4-4464eba81d95</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_ImageConstants.ImagesFieldName)]
				public virtual IEnumerable<Guid> Images  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ICarouselFolder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/CarouselFolder</para>	
	/// <para>ID: 53946f7d-c85f-412a-9a0d-27e92c7a9c68</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselFolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICarouselFolder : IGlassBase 
	{
			
	}


	public static partial class ICarouselFolderConstants{

			public const string TemplateIdString = "53946f7d-c85f-412a-9a0d-27e92c7a9c68";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "CarouselFolder";

			

	}

	
	/// <summary>
	/// CarouselFolder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/CarouselFolder</para>	
	/// <para>ID: 53946f7d-c85f-412a-9a0d-27e92c7a9c68</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselFolderConstants.TemplateIdString)] //, Cachable = true
	public partial class CarouselFolder  : GlassBase, ICarouselFolder 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Base_Heading_Decoration Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Heading Decoration</para>	
	/// <para>ID: 5ce005b7-1866-4d56-a9fb-795b8069fb2c</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Heading_DecorationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Heading_Decoration : IGlassBase 
	{
			
					/// <summary>
					/// The DecorationBanner field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: d7f9eb29-08da-4f6d-b69d-f0fb0ccfc4b2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Heading_DecorationConstants.DecorationBannerFieldName)]
					string DecorationBanner  {get; set;}
			
			
	}


	public static partial class I_Base_Heading_DecorationConstants{

			public const string TemplateIdString = "5ce005b7-1866-4d56-a9fb-795b8069fb2c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Heading Decoration";

		
			
			public static readonly ID DecorationBannerFieldId = new ID("d7f9eb29-08da-4f6d-b69d-f0fb0ccfc4b2");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
			

	}

	
	/// <summary>
	/// _Base_Heading_Decoration
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Heading Decoration</para>	
	/// <para>ID: 5ce005b7-1866-4d56-a9fb-795b8069fb2c</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Heading_DecorationConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Heading_Decoration  : GlassBase, I_Base_Heading_Decoration 
	{
	   
		
				/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d7f9eb29-08da-4f6d-b69d-f0fb0ccfc4b2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Heading_DecorationConstants.DecorationBannerFieldName)]
				public virtual string DecorationBanner  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IRecipesDetails Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/RecipesDetails</para>	
	/// <para>ID: 621d205c-d480-46ea-8402-2ca389850b8a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipesDetailsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IRecipesDetails : IGlassBase 
	{
			
					/// <summary>
					/// The description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: f0eabda0-dd0e-4124-88c0-803a80b32b2b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The ingredients field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 0c30b514-f3cb-4906-b00c-6783b89304fe</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.IngredientsFieldName)]
					string Ingredients  {get; set;}
			
			
					/// <summary>
					/// The metatitle field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 6a2f9a00-56b3-4139-8bfe-be5004a8aa67</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.MetatitleFieldName)]
					string Metatitle  {get; set;}
			
			
					/// <summary>
					/// The image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 50a63ba6-b639-479d-8f02-890afc7f3dfb</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.ImageFieldName)]
					Image Image  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 4eb1fd71-5d39-4831-912e-d0c8ad6d54e0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
					/// <summary>
					/// The Duration field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8eef9af4-1b4d-447e-a476-e533aa98550f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.DurationFieldName)]
					string Duration  {get; set;}
			
			
					/// <summary>
					/// The skill level field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 06cd6194-10b7-488c-a730-168a7df592f0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.Skill_LevelFieldName)]
					string Skill_Level  {get; set;}
			
			
					/// <summary>
					/// The type field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 873857a2-c86c-4edd-92cb-b5d64925fc60</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesDetailsConstants.TypeFieldName)]
					string Type  {get; set;}
			
			
	}


	public static partial class IRecipesDetailsConstants{

			public const string TemplateIdString = "621d205c-d480-46ea-8402-2ca389850b8a";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "RecipesDetails";

		
			
			public static readonly ID DescriptionFieldId = new ID("f0eabda0-dd0e-4124-88c0-803a80b32b2b");
			public const string DescriptionFieldName = "description";
			
		
			
			public static readonly ID IngredientsFieldId = new ID("0c30b514-f3cb-4906-b00c-6783b89304fe");
			public const string IngredientsFieldName = "ingredients";
			
		
			
			public static readonly ID MetatitleFieldId = new ID("6a2f9a00-56b3-4139-8bfe-be5004a8aa67");
			public const string MetatitleFieldName = "metatitle";
			
		
			
			public static readonly ID ImageFieldId = new ID("50a63ba6-b639-479d-8f02-890afc7f3dfb");
			public const string ImageFieldName = "image";
			
		
			
			public static readonly ID TitleFieldId = new ID("4eb1fd71-5d39-4831-912e-d0c8ad6d54e0");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID DurationFieldId = new ID("8eef9af4-1b4d-447e-a476-e533aa98550f");
			public const string DurationFieldName = "Duration";
			
		
			
			public static readonly ID Skill_LevelFieldId = new ID("06cd6194-10b7-488c-a730-168a7df592f0");
			public const string Skill_LevelFieldName = "skill level";
			
		
			
			public static readonly ID TypeFieldId = new ID("873857a2-c86c-4edd-92cb-b5d64925fc60");
			public const string TypeFieldName = "type";
			
			

	}

	
	/// <summary>
	/// RecipesDetails
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/RecipesDetails</para>	
	/// <para>ID: 621d205c-d480-46ea-8402-2ca389850b8a</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipesDetailsConstants.TemplateIdString)] //, Cachable = true
	public partial class RecipesDetails  : GlassBase, IRecipesDetails 
	{
	   
		
				/// <summary>
				/// The description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: f0eabda0-dd0e-4124-88c0-803a80b32b2b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The ingredients field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 0c30b514-f3cb-4906-b00c-6783b89304fe</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.IngredientsFieldName)]
				public virtual string Ingredients  {get; set;}
					
		
				/// <summary>
				/// The metatitle field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 6a2f9a00-56b3-4139-8bfe-be5004a8aa67</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.MetatitleFieldName)]
				public virtual string Metatitle  {get; set;}
					
		
				/// <summary>
				/// The image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 50a63ba6-b639-479d-8f02-890afc7f3dfb</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 4eb1fd71-5d39-4831-912e-d0c8ad6d54e0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Duration field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8eef9af4-1b4d-447e-a476-e533aa98550f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.DurationFieldName)]
				public virtual string Duration  {get; set;}
					
		
				/// <summary>
				/// The skill level field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 06cd6194-10b7-488c-a730-168a7df592f0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.Skill_LevelFieldName)]
				public virtual string Skill_Level  {get; set;}
					
		
				/// <summary>
				/// The type field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 873857a2-c86c-4edd-92cb-b5d64925fc60</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesDetailsConstants.TypeFieldName)]
				public virtual string Type  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ISamplePage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/SamplePage</para>	
	/// <para>ID: 75cf3c95-e456-4f52-b0fc-333ee056e95b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISamplePageConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISamplePage : IGlassBase 
	{
			
	}


	public static partial class ISamplePageConstants{

			public const string TemplateIdString = "75cf3c95-e456-4f52-b0fc-333ee056e95b";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SamplePage";

			

	}

	
	/// <summary>
	/// SamplePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/SamplePage</para>	
	/// <para>ID: 75cf3c95-e456-4f52-b0fc-333ee056e95b</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISamplePageConstants.TemplateIdString)] //, Cachable = true
	public partial class SamplePage  : GlassBase, ISamplePage 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Base_Navigation Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Navigation</para>	
	/// <para>ID: 8ded2ff8-3c46-4698-93bf-d38923aea232</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_NavigationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Navigation : IGlassBase 
	{
			
					/// <summary>
					/// The ExcludeFromNavigation field.
					/// <para></para>
					/// <para>Field Type: Checkbox</para>		
					/// <para>Field ID: 4f636117-0cd6-4b1f-a6da-d7755027ede3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_NavigationConstants.ExcludeFromNavigationFieldName)]
					bool ExcludeFromNavigation  {get; set;}
			
			
	}


	public static partial class I_Base_NavigationConstants{

			public const string TemplateIdString = "8ded2ff8-3c46-4698-93bf-d38923aea232";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Navigation";

		
			
			public static readonly ID ExcludeFromNavigationFieldId = new ID("4f636117-0cd6-4b1f-a6da-d7755027ede3");
			public const string ExcludeFromNavigationFieldName = "ExcludeFromNavigation";
			
			

	}

	
	/// <summary>
	/// _Base_Navigation
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Navigation</para>	
	/// <para>ID: 8ded2ff8-3c46-4698-93bf-d38923aea232</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_NavigationConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Navigation  : GlassBase, I_Base_Navigation 
	{
	   
		
				/// <summary>
				/// The ExcludeFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// <para>Field ID: 4f636117-0cd6-4b1f-a6da-d7755027ede3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_NavigationConstants.ExcludeFromNavigationFieldName)]
				public virtual bool ExcludeFromNavigation  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ICategory Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/Category</para>	
	/// <para>ID: 8e37d577-d840-4cd2-8ca7-2377cbc74262</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICategoryConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICategory : IGlassBase 
	{
			
	}


	public static partial class ICategoryConstants{

			public const string TemplateIdString = "8e37d577-d840-4cd2-8ca7-2377cbc74262";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Category";

			

	}

	
	/// <summary>
	/// Category
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/Category</para>	
	/// <para>ID: 8e37d577-d840-4cd2-8ca7-2377cbc74262</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICategoryConstants.TemplateIdString)] //, Cachable = true
	public partial class Category  : GlassBase, ICategory 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Base_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Content</para>	
	/// <para>ID: 980a4ffc-714c-42e3-b93c-70186433efd7</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Content : IGlassBase 
	{
			
					/// <summary>
					/// The ContentHeading field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 8f78b690-6420-4356-9cc5-617e4caaae5e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_ContentConstants.ContentHeadingFieldName)]
					string ContentHeading  {get; set;}
			
			
					/// <summary>
					/// The ContentIntro field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 082cb685-77be-4972-a846-ed9db631e1cc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_ContentConstants.ContentIntroFieldName)]
					string ContentIntro  {get; set;}
			
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 7e49c2b2-4ba6-4ba4-ab1b-36c7e976b4d6</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_ContentConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
	}


	public static partial class I_Base_ContentConstants{

			public const string TemplateIdString = "980a4ffc-714c-42e3-b93c-70186433efd7";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Content";

		
			
			public static readonly ID ContentHeadingFieldId = new ID("8f78b690-6420-4356-9cc5-617e4caaae5e");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("082cb685-77be-4972-a846-ed9db631e1cc");
			public const string ContentIntroFieldName = "ContentIntro";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("7e49c2b2-4ba6-4ba4-ab1b-36c7e976b4d6");
			public const string DescriptionFieldName = "Description";
			
			

	}

	
	/// <summary>
	/// _Base_Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Content</para>	
	/// <para>ID: 980a4ffc-714c-42e3-b93c-70186433efd7</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_ContentConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Content  : GlassBase, I_Base_Content 
	{
	   
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8f78b690-6420-4356-9cc5-617e4caaae5e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_ContentConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 082cb685-77be-4972-a846-ed9db631e1cc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_ContentConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 7e49c2b2-4ba6-4ba4-ab1b-36c7e976b4d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_ContentConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Base_Meta_Information Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Meta Information</para>	
	/// <para>ID: a59a1dd6-c3dd-490e-9b89-c6a1ed028a48</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Meta_InformationConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Base_Meta_Information : IGlassBase 
	{
			
					/// <summary>
					/// The MetaDescription field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 3edda3cb-87a3-4f76-a2f8-6120bb2ba350</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Meta_InformationConstants.MetaDescriptionFieldName)]
					string MetaDescription  {get; set;}
			
			
					/// <summary>
					/// The MetaTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a65570d8-480c-4907-861c-d630eba2d4c3</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_Base_Meta_InformationConstants.MetaTitleFieldName)]
					string MetaTitle  {get; set;}
			
			
	}


	public static partial class I_Base_Meta_InformationConstants{

			public const string TemplateIdString = "a59a1dd6-c3dd-490e-9b89-c6a1ed028a48";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Base Meta Information";

		
			
			public static readonly ID MetaDescriptionFieldId = new ID("3edda3cb-87a3-4f76-a2f8-6120bb2ba350");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("a65570d8-480c-4907-861c-d630eba2d4c3");
			public const string MetaTitleFieldName = "MetaTitle";
			
			

	}

	
	/// <summary>
	/// _Base_Meta_Information
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Base Meta Information</para>	
	/// <para>ID: a59a1dd6-c3dd-490e-9b89-c6a1ed028a48</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_Base_Meta_InformationConstants.TemplateIdString)] //, Cachable = true
	public partial class _Base_Meta_Information  : GlassBase, I_Base_Meta_Information 
	{
	   
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3edda3cb-87a3-4f76-a2f8-6120bb2ba350</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Meta_InformationConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a65570d8-480c-4907-861c-d630eba2d4c3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_Base_Meta_InformationConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ILink Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/Navigation/Link</para>	
	/// <para>ID: a5cf18ab-5a5f-426b-93ce-dcd769e81be8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILinkConstants.TemplateIdString )] //, Cachable = true
	public partial interface ILink : IGlassBase 
	{
			
					/// <summary>
					/// The NavLink field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 3037f223-a747-4e17-b2c9-47af22471016</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ILinkConstants.NavLinkFieldName)]
					Link NavLink  {get; set;}
			
			
	}


	public static partial class ILinkConstants{

			public const string TemplateIdString = "a5cf18ab-5a5f-426b-93ce-dcd769e81be8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Link";

		
			
			public static readonly ID NavLinkFieldId = new ID("3037f223-a747-4e17-b2c9-47af22471016");
			public const string NavLinkFieldName = "NavLink";
			
			

	}

	
	/// <summary>
	/// Link
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/Navigation/Link</para>	
	/// <para>ID: a5cf18ab-5a5f-426b-93ce-dcd769e81be8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ILinkConstants.TemplateIdString)] //, Cachable = true
	public partial class Link  : GlassBase, ILink 
	{
	   
		
				/// <summary>
				/// The NavLink field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 3037f223-a747-4e17-b2c9-47af22471016</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ILinkConstants.NavLinkFieldName)]
				public virtual Link NavLink  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ISite_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Site Folder</para>	
	/// <para>ID: aa2cbd07-ce19-449b-ad48-1784ae720349</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite_Folder : IGlassBase 
	{
			
	}


	public static partial class ISite_FolderConstants{

			public const string TemplateIdString = "aa2cbd07-ce19-449b-ad48-1784ae720349";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site Folder";

			

	}

	
	/// <summary>
	/// Site_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Site Folder</para>	
	/// <para>ID: aa2cbd07-ce19-449b-ad48-1784ae720349</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISite_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Site_Folder  : GlassBase, ISite_Folder 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_PageNotFound Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_PageNotFound</para>	
	/// <para>ID: ab9a0aca-7469-4650-889e-cb0f42270e39</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_PageNotFoundConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_PageNotFound : IGlassBase 
	{
			
					/// <summary>
					/// The ErrorPage field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: caef0675-bdca-467e-9270-d0c925aecc74</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_PageNotFoundConstants.ErrorPageFieldName)]
					Link ErrorPage  {get; set;}
			
			
	}


	public static partial class I_PageNotFoundConstants{

			public const string TemplateIdString = "ab9a0aca-7469-4650-889e-cb0f42270e39";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_PageNotFound";

		
			
			public static readonly ID ErrorPageFieldId = new ID("caef0675-bdca-467e-9270-d0c925aecc74");
			public const string ErrorPageFieldName = "ErrorPage";
			
			

	}

	
	/// <summary>
	/// _PageNotFound
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_PageNotFound</para>	
	/// <para>ID: ab9a0aca-7469-4650-889e-cb0f42270e39</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_PageNotFoundConstants.TemplateIdString)] //, Cachable = true
	public partial class _PageNotFound  : GlassBase, I_PageNotFound 
	{
	   
		
				/// <summary>
				/// The ErrorPage field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: caef0675-bdca-467e-9270-d0c925aecc74</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_PageNotFoundConstants.ErrorPageFieldName)]
				public virtual Link ErrorPage  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ISinglePage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/SinglePage</para>	
	/// <para>ID: ac91c0fc-39ec-4ed7-b7df-354823dbe7f4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISinglePageConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISinglePage : IGlassBase , global::Foundation.Serialization.I_Base_Content
	{
			
	}


	public static partial class ISinglePageConstants{

			public const string TemplateIdString = "ac91c0fc-39ec-4ed7-b7df-354823dbe7f4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SinglePage";

		
			
			public static readonly ID ContentHeadingFieldId = new ID("8f78b690-6420-4356-9cc5-617e4caaae5e");
			public const string ContentHeadingFieldName = "ContentHeading";
			
		
			
			public static readonly ID ContentIntroFieldId = new ID("082cb685-77be-4972-a846-ed9db631e1cc");
			public const string ContentIntroFieldName = "ContentIntro";
			
		
			
			public static readonly ID DescriptionFieldId = new ID("7e49c2b2-4ba6-4ba4-ab1b-36c7e976b4d6");
			public const string DescriptionFieldName = "Description";
			
			

	}

	
	/// <summary>
	/// SinglePage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/SinglePage</para>	
	/// <para>ID: ac91c0fc-39ec-4ed7-b7df-354823dbe7f4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISinglePageConstants.TemplateIdString)] //, Cachable = true
	public partial class SinglePage  : GlassBase, ISinglePage 
	{
	   
		
				/// <summary>
				/// The ContentHeading field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 8f78b690-6420-4356-9cc5-617e4caaae5e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISinglePageConstants.ContentHeadingFieldName)]
				public virtual string ContentHeading  {get; set;}
					
		
				/// <summary>
				/// The ContentIntro field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 082cb685-77be-4972-a846-ed9db631e1cc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISinglePageConstants.ContentIntroFieldName)]
				public virtual string ContentIntro  {get; set;}
					
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 7e49c2b2-4ba6-4ba4-ab1b-36c7e976b4d6</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISinglePageConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IAboutUs Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/AboutUs/AboutUs</para>	
	/// <para>ID: b0bf8fe4-9f69-4e28-8eb0-6786fb9337e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAboutUsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IAboutUs : IGlassBase 
	{
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 01596921-2f61-4600-ba93-d20e1ef1e8a2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAboutUsConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 22f9bfb3-adfe-4f17-986e-0213ba0b9b3a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAboutUsConstants.ImageFieldName)]
					Image Image  {get; set;}
			
			
					/// <summary>
					/// The SubTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b1aed021-6cbe-42d7-be6c-042d55c30f61</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAboutUsConstants.SubTitleFieldName)]
					string SubTitle  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: a8a52b05-0806-47c9-b963-09358ce9e5cf</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IAboutUsConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class IAboutUsConstants{

			public const string TemplateIdString = "b0bf8fe4-9f69-4e28-8eb0-6786fb9337e1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "AboutUs";

		
			
			public static readonly ID DescriptionFieldId = new ID("01596921-2f61-4600-ba93-d20e1ef1e8a2");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID ImageFieldId = new ID("22f9bfb3-adfe-4f17-986e-0213ba0b9b3a");
			public const string ImageFieldName = "Image";
			
		
			
			public static readonly ID SubTitleFieldId = new ID("b1aed021-6cbe-42d7-be6c-042d55c30f61");
			public const string SubTitleFieldName = "SubTitle";
			
		
			
			public static readonly ID TitleFieldId = new ID("a8a52b05-0806-47c9-b963-09358ce9e5cf");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// AboutUs
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/AboutUs/AboutUs</para>	
	/// <para>ID: b0bf8fe4-9f69-4e28-8eb0-6786fb9337e1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IAboutUsConstants.TemplateIdString)] //, Cachable = true
	public partial class AboutUs  : GlassBase, IAboutUs 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 01596921-2f61-4600-ba93-d20e1ef1e8a2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAboutUsConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 22f9bfb3-adfe-4f17-986e-0213ba0b9b3a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAboutUsConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
		
				/// <summary>
				/// The SubTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b1aed021-6cbe-42d7-be6c-042d55c30f61</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAboutUsConstants.SubTitleFieldName)]
				public virtual string SubTitle  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a8a52b05-0806-47c9-b963-09358ce9e5cf</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IAboutUsConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ISite Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Site</para>	
	/// <para>ID: b69c8962-9df7-4edd-a394-fce29c1da1d8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISite : IGlassBase 
	{
			
	}


	public static partial class ISiteConstants{

			public const string TemplateIdString = "b69c8962-9df7-4edd-a394-fce29c1da1d8";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Site";

			

	}

	
	/// <summary>
	/// Site
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Site</para>	
	/// <para>ID: b69c8962-9df7-4edd-a394-fce29c1da1d8</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteConstants.TemplateIdString)] //, Cachable = true
	public partial class Site  : GlassBase, ISite 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IRecipesCategory Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipesCategory</para>	
	/// <para>ID: b713c823-b62f-4ada-a272-8c8163ae06e4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipesCategoryConstants.TemplateIdString )] //, Cachable = true
	public partial interface IRecipesCategory : IGlassBase 
	{
			
					/// <summary>
					/// The Category Name field.
					/// <para></para>
					/// <para>Field Type: Droplink</para>		
					/// <para>Field ID: 01ff8d12-fbce-4ba6-9ad0-4a08e27c0e04</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipesCategoryConstants.Category_NameFieldName)]
					Guid Category_Name  {get; set;}
			
			
	}


	public static partial class IRecipesCategoryConstants{

			public const string TemplateIdString = "b713c823-b62f-4ada-a272-8c8163ae06e4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "RecipesCategory";

		
			
			public static readonly ID Category_NameFieldId = new ID("01ff8d12-fbce-4ba6-9ad0-4a08e27c0e04");
			public const string Category_NameFieldName = "Category Name";
			
			

	}

	
	/// <summary>
	/// RecipesCategory
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipesCategory</para>	
	/// <para>ID: b713c823-b62f-4ada-a272-8c8163ae06e4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipesCategoryConstants.TemplateIdString)] //, Cachable = true
	public partial class RecipesCategory  : GlassBase, IRecipesCategory 
	{
	   
		
				/// <summary>
				/// The Category Name field.
				/// <para></para>
				/// <para>Field Type: Droplink</para>		
				/// <para>Field ID: 01ff8d12-fbce-4ba6-9ad0-4a08e27c0e04</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipesCategoryConstants.Category_NameFieldName)]
				public virtual Guid Category_Name  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IRecipeDetail Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipeDetail</para>	
	/// <para>ID: b82a44e4-da5b-4cb3-b9eb-d0b0dae0fb0e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeDetailConstants.TemplateIdString )] //, Cachable = true
	public partial interface IRecipeDetail : IGlassBase , global::Foundation.Serialization.IRecipesCategory
	{
			
					/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: f4f85c45-6a19-4077-af43-e2604841aad0</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
			
					/// <summary>
					/// The Ingredients field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 99469264-5372-4471-be20-397f38eb4964</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.IngredientsFieldName)]
					string Ingredients  {get; set;}
			
			
					/// <summary>
					/// The MetaTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 7c12cc36-14a5-4736-ae13-58f111618954</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.MetaTitleFieldName)]
					string MetaTitle  {get; set;}
			
			
					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: e20b7c62-4944-49c3-b218-9975088a9fa9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.ImageFieldName)]
					Image Image  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 826b903c-dc32-4a5b-a01b-4466dd080354</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
					/// <summary>
					/// The Duration field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 9185455e-9c23-42b0-9e11-2bea9fcd316e</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.DurationFieldName)]
					string Duration  {get; set;}
			
			
					/// <summary>
					/// The Skill Level field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 6b98564c-1928-4420-bc8a-a5cbac88a069</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.Skill_LevelFieldName)]
					string Skill_Level  {get; set;}
			
			
					/// <summary>
					/// The Type field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: c0be06c4-6587-4c39-a1c6-a0c716b94d0f</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IRecipeDetailConstants.TypeFieldName)]
					string Type  {get; set;}
			
			
	}


	public static partial class IRecipeDetailConstants{

			public const string TemplateIdString = "b82a44e4-da5b-4cb3-b9eb-d0b0dae0fb0e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "RecipeDetail";

		
			
			public static readonly ID DescriptionFieldId = new ID("f4f85c45-6a19-4077-af43-e2604841aad0");
			public const string DescriptionFieldName = "Description";
			
		
			
			public static readonly ID IngredientsFieldId = new ID("99469264-5372-4471-be20-397f38eb4964");
			public const string IngredientsFieldName = "Ingredients";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("7c12cc36-14a5-4736-ae13-58f111618954");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID ImageFieldId = new ID("e20b7c62-4944-49c3-b218-9975088a9fa9");
			public const string ImageFieldName = "Image";
			
		
			
			public static readonly ID TitleFieldId = new ID("826b903c-dc32-4a5b-a01b-4466dd080354");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID DurationFieldId = new ID("9185455e-9c23-42b0-9e11-2bea9fcd316e");
			public const string DurationFieldName = "Duration";
			
		
			
			public static readonly ID Skill_LevelFieldId = new ID("6b98564c-1928-4420-bc8a-a5cbac88a069");
			public const string Skill_LevelFieldName = "Skill Level";
			
		
			
			public static readonly ID TypeFieldId = new ID("c0be06c4-6587-4c39-a1c6-a0c716b94d0f");
			public const string TypeFieldName = "Type";
			
		
			
			public static readonly ID Category_NameFieldId = new ID("01ff8d12-fbce-4ba6-9ad0-4a08e27c0e04");
			public const string Category_NameFieldName = "Category Name";
			
			

	}

	
	/// <summary>
	/// RecipeDetail
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipeDetail</para>	
	/// <para>ID: b82a44e4-da5b-4cb3-b9eb-d0b0dae0fb0e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeDetailConstants.TemplateIdString)] //, Cachable = true
	public partial class RecipeDetail  : GlassBase, IRecipeDetail 
	{
	   
		
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: f4f85c45-6a19-4077-af43-e2604841aad0</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
		
				/// <summary>
				/// The Ingredients field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 99469264-5372-4471-be20-397f38eb4964</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.IngredientsFieldName)]
				public virtual string Ingredients  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 7c12cc36-14a5-4736-ae13-58f111618954</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: e20b7c62-4944-49c3-b218-9975088a9fa9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 826b903c-dc32-4a5b-a01b-4466dd080354</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The Duration field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 9185455e-9c23-42b0-9e11-2bea9fcd316e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.DurationFieldName)]
				public virtual string Duration  {get; set;}
					
		
				/// <summary>
				/// The Skill Level field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 6b98564c-1928-4420-bc8a-a5cbac88a069</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.Skill_LevelFieldName)]
				public virtual string Skill_Level  {get; set;}
					
		
				/// <summary>
				/// The Type field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: c0be06c4-6587-4c39-a1c6-a0c716b94d0f</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.TypeFieldName)]
				public virtual string Type  {get; set;}
					
		
				/// <summary>
				/// The Category Name field.
				/// <para></para>
				/// <para>Field Type: Droplink</para>		
				/// <para>Field ID: 01ff8d12-fbce-4ba6-9ad0-4a08e27c0e04</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeDetailConstants.Category_NameFieldName)]
				public virtual Guid Category_Name  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IHeader Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/Navigation/Header</para>	
	/// <para>ID: bb3f2571-14cf-4978-a105-26485efe283e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeaderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IHeader : IGlassBase 
	{
			
					/// <summary>
					/// The banner field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: e76c5683-a5bd-433a-aa63-3d4019a2372c</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.BannerFieldName)]
					Image Banner  {get; set;}
			
			
					/// <summary>
					/// The Logo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 8d62d898-ea2d-4d63-812b-9940ef4ef881</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.LogoFieldName)]
					Image Logo  {get; set;}
			
			
					/// <summary>
					/// The LogoLink field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 73585b79-1798-4707-b900-f2576343083d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IHeaderConstants.LogoLinkFieldName)]
					Link LogoLink  {get; set;}
			
			
	}


	public static partial class IHeaderConstants{

			public const string TemplateIdString = "bb3f2571-14cf-4978-a105-26485efe283e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Header";

		
			
			public static readonly ID BannerFieldId = new ID("e76c5683-a5bd-433a-aa63-3d4019a2372c");
			public const string BannerFieldName = "banner";
			
		
			
			public static readonly ID LogoFieldId = new ID("8d62d898-ea2d-4d63-812b-9940ef4ef881");
			public const string LogoFieldName = "Logo";
			
		
			
			public static readonly ID LogoLinkFieldId = new ID("73585b79-1798-4707-b900-f2576343083d");
			public const string LogoLinkFieldName = "LogoLink";
			
			

	}

	
	/// <summary>
	/// Header
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/Navigation/Header</para>	
	/// <para>ID: bb3f2571-14cf-4978-a105-26485efe283e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IHeaderConstants.TemplateIdString)] //, Cachable = true
	public partial class Header  : GlassBase, IHeader 
	{
	   
		
				/// <summary>
				/// The banner field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: e76c5683-a5bd-433a-aa63-3d4019a2372c</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.BannerFieldName)]
				public virtual Image Banner  {get; set;}
					
		
				/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 8d62d898-ea2d-4d63-812b-9940ef4ef881</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
		
				/// <summary>
				/// The LogoLink field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 73585b79-1798-4707-b900-f2576343083d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IHeaderConstants.LogoLinkFieldName)]
				public virtual Link LogoLink  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ISlide Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/Slide</para>	
	/// <para>ID: bca81128-695f-4c57-872c-b05fb1b4c6c1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISlideConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISlide : IGlassBase 
	{
			
					/// <summary>
					/// The CTA field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 759620f5-2dec-4be4-a58c-e59c54413ebd</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISlideConstants.CTAFieldName)]
					Link CTA  {get; set;}
			
			
					/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: e6d5ea34-694c-4fe1-b3ee-6cda340c273b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISlideConstants.ImageFieldName)]
					Image Image  {get; set;}
			
			
					/// <summary>
					/// The SubTitle field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b215f61c-3ecf-4f66-8a40-207eb56511af</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISlideConstants.SubTitleFieldName)]
					string SubTitle  {get; set;}
			
			
					/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 91b648c4-84fe-40da-90d5-6d453350aa84</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISlideConstants.TitleFieldName)]
					string Title  {get; set;}
			
			
	}


	public static partial class ISlideConstants{

			public const string TemplateIdString = "bca81128-695f-4c57-872c-b05fb1b4c6c1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Slide";

		
			
			public static readonly ID CTAFieldId = new ID("759620f5-2dec-4be4-a58c-e59c54413ebd");
			public const string CTAFieldName = "CTA";
			
		
			
			public static readonly ID ImageFieldId = new ID("e6d5ea34-694c-4fe1-b3ee-6cda340c273b");
			public const string ImageFieldName = "Image";
			
		
			
			public static readonly ID SubTitleFieldId = new ID("b215f61c-3ecf-4f66-8a40-207eb56511af");
			public const string SubTitleFieldName = "SubTitle";
			
		
			
			public static readonly ID TitleFieldId = new ID("91b648c4-84fe-40da-90d5-6d453350aa84");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// Slide
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/Slide</para>	
	/// <para>ID: bca81128-695f-4c57-872c-b05fb1b4c6c1</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISlideConstants.TemplateIdString)] //, Cachable = true
	public partial class Slide  : GlassBase, ISlide 
	{
	   
		
				/// <summary>
				/// The CTA field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 759620f5-2dec-4be4-a58c-e59c54413ebd</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.CTAFieldName)]
				public virtual Link CTA  {get; set;}
					
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: e6d5ea34-694c-4fe1-b3ee-6cda340c273b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
		
				/// <summary>
				/// The SubTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b215f61c-3ecf-4f66-8a40-207eb56511af</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.SubTitleFieldName)]
				public virtual string SubTitle  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 91b648c4-84fe-40da-90d5-6d453350aa84</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISlideConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IRecipeImage Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipeImage</para>	
	/// <para>ID: c028dcd0-e9a8-48bc-ac85-555316522249</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeImageConstants.TemplateIdString )] //, Cachable = true
	public partial interface IRecipeImage : IGlassBase , global::Foundation.Serialization.I_Base_Image, global::Foundation.Serialization.I_Title, global::Foundation.Serialization.I_Base_Meta_Information, global::Foundation.Serialization.I_Base_Heading_Decoration
	{
			
	}


	public static partial class IRecipeImageConstants{

			public const string TemplateIdString = "c028dcd0-e9a8-48bc-ac85-555316522249";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "RecipeImage";

		
			
			public static readonly ID ImagesFieldId = new ID("fc580838-74b5-4372-b1f4-4464eba81d95");
			public const string ImagesFieldName = "Image";
			
		
			
			public static readonly ID TitleFieldId = new ID("ae26dccd-dfce-4443-a5dc-6f219439e23e");
			public const string TitleFieldName = "Title";
			
		
			
			public static readonly ID MetaDescriptionFieldId = new ID("3edda3cb-87a3-4f76-a2f8-6120bb2ba350");
			public const string MetaDescriptionFieldName = "MetaDescription";
			
		
			
			public static readonly ID MetaTitleFieldId = new ID("a65570d8-480c-4907-861c-d630eba2d4c3");
			public const string MetaTitleFieldName = "MetaTitle";
			
		
			
			public static readonly ID DecorationBannerFieldId = new ID("d7f9eb29-08da-4f6d-b69d-f0fb0ccfc4b2");
			public const string DecorationBannerFieldName = "DecorationBanner";
			
			

	}

	
	/// <summary>
	/// RecipeImage
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Data Template/RecipeImage</para>	
	/// <para>ID: c028dcd0-e9a8-48bc-ac85-555316522249</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeImageConstants.TemplateIdString)] //, Cachable = true
	public partial class RecipeImage  : GlassBase, IRecipeImage 
	{
	   
		
				/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// <para>Field ID: fc580838-74b5-4372-b1f4-4464eba81d95</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeImageConstants.ImagesFieldName)]
				public virtual IEnumerable<Guid> Images  {get; set;}
					
		
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: ae26dccd-dfce-4443-a5dc-6f219439e23e</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeImageConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
		
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 3edda3cb-87a3-4f76-a2f8-6120bb2ba350</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeImageConstants.MetaDescriptionFieldName)]
				public virtual string MetaDescription  {get; set;}
					
		
				/// <summary>
				/// The MetaTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: a65570d8-480c-4907-861c-d630eba2d4c3</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeImageConstants.MetaTitleFieldName)]
				public virtual string MetaTitle  {get; set;}
					
		
				/// <summary>
				/// The DecorationBanner field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: d7f9eb29-08da-4f6d-b69d-f0fb0ccfc4b2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IRecipeImageConstants.DecorationBannerFieldName)]
				public virtual string DecorationBanner  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ICarousel Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/Carousel</para>	
	/// <para>ID: cede861b-3c04-44d9-8b25-977d99e8e904</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString )] //, Cachable = true
	public partial interface ICarousel : IGlassBase 
	{
			
					/// <summary>
					/// The Slides field.
					/// <para></para>
					/// <para>Field Type: Treelist</para>		
					/// <para>Field ID: 5fd5304f-cc80-4989-9b2d-f3482935e6b8</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ICarouselConstants.SlidesFieldName)]
					IEnumerable<Guid> Slides  {get; set;}
			
			
	}


	public static partial class ICarouselConstants{

			public const string TemplateIdString = "cede861b-3c04-44d9-8b25-977d99e8e904";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Carousel";

		
			
			public static readonly ID SlidesFieldId = new ID("5fd5304f-cc80-4989-9b2d-f3482935e6b8");
			public const string SlidesFieldName = "Slides";
			
			

	}

	
	/// <summary>
	/// Carousel
	/// <para></para>
	/// <para>Path: /sitecore/templates/Feature/FarmToFork/New Carousel Template/Carousel</para>	
	/// <para>ID: cede861b-3c04-44d9-8b25-977d99e8e904</para>	
	/// </summary>
	[SitecoreType(TemplateId=ICarouselConstants.TemplateIdString)] //, Cachable = true
	public partial class Carousel  : GlassBase, ICarousel 
	{
	   
		
				/// <summary>
				/// The Slides field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// <para>Field ID: 5fd5304f-cc80-4989-9b2d-f3482935e6b8</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ICarouselConstants.SlidesFieldName)]
				public virtual IEnumerable<Guid> Slides  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IPromo Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/Promo</para>	
	/// <para>ID: d4ddd411-4c00-4f84-b07f-05ede849c7cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPromoConstants.TemplateIdString )] //, Cachable = true
	public partial interface IPromo : IGlassBase 
	{
			
	}


	public static partial class IPromoConstants{

			public const string TemplateIdString = "d4ddd411-4c00-4f84-b07f-05ede849c7cd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Promo";

			

	}

	
	/// <summary>
	/// Promo
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/Promo</para>	
	/// <para>ID: d4ddd411-4c00-4f84-b07f-05ede849c7cd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IPromoConstants.TemplateIdString)] //, Cachable = true
	public partial class Promo  : GlassBase, IPromo 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IMultiList Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/MultiList</para>	
	/// <para>ID: e474e3bb-494c-461c-9de7-ccf58e677c09</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMultiListConstants.TemplateIdString )] //, Cachable = true
	public partial interface IMultiList : IGlassBase 
	{
			
	}


	public static partial class IMultiListConstants{

			public const string TemplateIdString = "e474e3bb-494c-461c-9de7-ccf58e677c09";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "MultiList";

			

	}

	
	/// <summary>
	/// MultiList
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/MultiList</para>	
	/// <para>ID: e474e3bb-494c-461c-9de7-ccf58e677c09</para>	
	/// </summary>
	[SitecoreType(TemplateId=IMultiListConstants.TemplateIdString)] //, Cachable = true
	public partial class MultiList  : GlassBase, IMultiList 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IRecipeDetails Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/RecipeDetails</para>	
	/// <para>ID: edf382f2-25e7-4558-a371-9d3bd5ed9ae4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeDetailsConstants.TemplateIdString )] //, Cachable = true
	public partial interface IRecipeDetails : IGlassBase 
	{
			
	}


	public static partial class IRecipeDetailsConstants{

			public const string TemplateIdString = "edf382f2-25e7-4558-a371-9d3bd5ed9ae4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "RecipeDetails";

			

	}

	
	/// <summary>
	/// RecipeDetails
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Folder Template/RecipeDetails</para>	
	/// <para>ID: edf382f2-25e7-4558-a371-9d3bd5ed9ae4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IRecipeDetailsConstants.TemplateIdString)] //, Cachable = true
	public partial class RecipeDetails  : GlassBase, IRecipeDetails 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// I_Content Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Content</para>	
	/// <para>ID: ef579e73-82f2-421f-800a-09ac894d2245</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_ContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface I_Content : IGlassBase 
	{
			
					/// <summary>
					/// The Content field.
					/// <para></para>
					/// <para>Field Type: Multi-Line Text</para>		
					/// <para>Field ID: 69047b4f-add7-4734-b55f-d329a44f72aa</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(I_ContentConstants.ContentFieldName)]
					string Content  {get; set;}
			
			
	}


	public static partial class I_ContentConstants{

			public const string TemplateIdString = "ef579e73-82f2-421f-800a-09ac894d2245";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "_Content";

		
			
			public static readonly ID ContentFieldId = new ID("69047b4f-add7-4734-b55f-d329a44f72aa");
			public const string ContentFieldName = "Content";
			
			

	}

	
	/// <summary>
	/// _Content
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Base Template/_Content</para>	
	/// <para>ID: ef579e73-82f2-421f-800a-09ac894d2245</para>	
	/// </summary>
	[SitecoreType(TemplateId=I_ContentConstants.TemplateIdString)] //, Cachable = true
	public partial class _Content  : GlassBase, I_Content 
	{
	   
		
				/// <summary>
				/// The Content field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// <para>Field ID: 69047b4f-add7-4734-b55f-d329a44f72aa</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(I_ContentConstants.ContentFieldName)]
				public virtual string Content  {get; set;}
					
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// ITenant_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Tenant Folder</para>	
	/// <para>ID: f2250c33-e006-45bf-ad1f-c3ce782a2852</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITenant_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface ITenant_Folder : IGlassBase 
	{
			
	}


	public static partial class ITenant_FolderConstants{

			public const string TemplateIdString = "f2250c33-e006-45bf-ad1f-c3ce782a2852";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Tenant Folder";

			

	}

	
	/// <summary>
	/// Tenant_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Tenant Folder</para>	
	/// <para>ID: f2250c33-e006-45bf-ad1f-c3ce782a2852</para>	
	/// </summary>
	[SitecoreType(TemplateId=ITenant_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Tenant_Folder  : GlassBase, ITenant_Folder 
	{
	   
			
	}

}
namespace Foundation.Serialization
{


 	/// <summary>
	/// IFooter Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Footer</para>	
	/// <para>ID: f64dbf59-61e6-4499-ba08-8276dc2bbefd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooterConstants.TemplateIdString )] //, Cachable = true
	public partial interface IFooter : IGlassBase 
	{
			
					/// <summary>
					/// The CopyRight field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 7f1186ec-b83a-4327-848d-2f53966ed87a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFooterConstants.CopyRightFieldName)]
					string CopyRight  {get; set;}
			
			
					/// <summary>
					/// The Logo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 9d4c1463-86ae-4863-829d-6791f663a917</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFooterConstants.LogoFieldName)]
					Image Logo  {get; set;}
			
			
					/// <summary>
					/// The LogoLink field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 130fb7d2-4392-491f-9483-486a6a1ef45a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFooterConstants.LogoLinkFieldName)]
					Link LogoLink  {get; set;}
			
			
					/// <summary>
					/// The theme field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: b7759fee-703c-40d8-849e-d867e67d55ab</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IFooterConstants.ThemeFieldName)]
					string Theme  {get; set;}
			
			
	}


	public static partial class IFooterConstants{

			public const string TemplateIdString = "f64dbf59-61e6-4499-ba08-8276dc2bbefd";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Footer";

		
			
			public static readonly ID CopyRightFieldId = new ID("7f1186ec-b83a-4327-848d-2f53966ed87a");
			public const string CopyRightFieldName = "CopyRight";
			
		
			
			public static readonly ID LogoFieldId = new ID("9d4c1463-86ae-4863-829d-6791f663a917");
			public const string LogoFieldName = "Logo";
			
		
			
			public static readonly ID LogoLinkFieldId = new ID("130fb7d2-4392-491f-9483-486a6a1ef45a");
			public const string LogoLinkFieldName = "LogoLink";
			
		
			
			public static readonly ID ThemeFieldId = new ID("b7759fee-703c-40d8-849e-d867e67d55ab");
			public const string ThemeFieldName = "theme";
			
			

	}

	
	/// <summary>
	/// Footer
	/// <para></para>
	/// <para>Path: /sitecore/templates/Project/FarmToFork/Footer</para>	
	/// <para>ID: f64dbf59-61e6-4499-ba08-8276dc2bbefd</para>	
	/// </summary>
	[SitecoreType(TemplateId=IFooterConstants.TemplateIdString)] //, Cachable = true
	public partial class Footer  : GlassBase, IFooter 
	{
	   
		
				/// <summary>
				/// The CopyRight field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 7f1186ec-b83a-4327-848d-2f53966ed87a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IFooterConstants.CopyRightFieldName)]
				public virtual string CopyRight  {get; set;}
					
		
				/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 9d4c1463-86ae-4863-829d-6791f663a917</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IFooterConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
		
				/// <summary>
				/// The LogoLink field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 130fb7d2-4392-491f-9483-486a6a1ef45a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IFooterConstants.LogoLinkFieldName)]
				public virtual Link LogoLink  {get; set;}
					
		
				/// <summary>
				/// The theme field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: b7759fee-703c-40d8-849e-d867e67d55ab</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IFooterConstants.ThemeFieldName)]
				public virtual string Theme  {get; set;}
					
			
	}

}
